examples/myapp/config/routes.rb
Rails.application.routes.draw do
  root to: 'tasks#index'

  resources :tasks
  post 'task/import', to: 'import_tasks#create'
end

examples/myapp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

examples/myapp/app/models/task.rb
class Task < ApplicationRecord
  enum state: { todo: 0, doing: 1, done: 2 }
end

examples/myapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

examples/myapp/app/controllers/import_tasks_controller.rb
require 'csv'

class ImportTasksController < ApplicationController
  rescue_from(StandardError) do |e|
    logger.error e

    redirect_to({ controller: :tasks, action: :index }, alert: 'Task import was failure')
  end

  def create
    file = params[:upload_file]

    csv = CSV.parse(file.read)

    ImportTaskJob.perform_later(csv)

    respond_to do |format|
      format.html { redirect_to({ controller: :tasks, action: :index }, notice: 'Task import was successfully started.') }
    end
  end
end

examples/myapp/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.page(params[:page])
  end

  def show
  end

  def new
    @task = Task.new
  end

  def edit
  end

  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def task_params
    params.require(:task).permit(:state, :name)
  end
end

examples/myapp/app/helpers/application_helper.rb
module ApplicationHelper
end

examples/myapp/app/helpers/import_tasks_helper.rb
module ImportTasksHelper
end

examples/myapp/app/helpers/tasks_helper.rb
module TasksHelper
end

examples/myapp/app/views/import_tasks/create.html.erb
<h1>ImportTasks#create</h1>
<p>Find me in app/views/import_tasks/create.html.erb</p>

examples/myapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

examples/myapp/app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :state %>
    <%= form.select :state, Task.states.keys.to_a, {} %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

examples/myapp/app/views/tasks/_import_form.html.erb
<%= form_with(url: task_import_path, local: true) do |form| %>
  <div class="field">
    <%= form.label :upload_file %>
    <%= form.file_field :upload_file %>
  </div>

  <div class="actions">
    <%= form.submit 'import CSV' %>
  </div>
<% end %>

examples/myapp/app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

examples/myapp/app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>
<% if alert %>
<p id="error_explanation"><%= alert %></p>
<% end %>

<h1>Tasks</h1>

<table>
  <thead>
    <tr>
      <th>State</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.state %></td>
        <td><%= task.name %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= paginate @tasks %>

<%= render 'import_form' %>

<%= link_to 'New Task', new_task_path %>

examples/myapp/app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

examples/myapp/app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>State:</strong>
  <%= @task.state %>
</p>

<p>
  <strong>Name:</strong>
  <%= @task.name %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>